version: 0.2
phases:
  install:
    commands:
      - yum update -y
      - yum install amazon-linux-extras -y
      - PYTHON=python2 amazon-linux-extras install docker -y
  pre_build:
    commands:
      - echo "Login to ECR"
      - if [ "$REPO_VISIBILITY" == "public" ]; then
          echo "Public"
          aws ecr-public get-login-password --region $REGION | docker login --username AWS --password-stdin public.ecr.aws
        else
          echo "Private"
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
        fi
  build:
    commands:
      - echo "Building image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - if [ "$REPO_VISIBILITY" == "public" ]; then
          echo "Public"
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $(aws ecr-public describe-repositories --region us-east-1 | grep repositoryUri | awk '{ print $2}' | tr -d "\"" | tr -d ","):$IMAGE_TAG
        else
          echo "Private"
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        fi
  post_build:
    commands:
      - echo "Pushing image to ECR"
      - if [ "$REPO_VISIBILITY" == "public" ]; then
          echo "Public"
          docker push $(aws ecr-public describe-repositories --region us-east-1 | grep repositoryUri | awk '{ print $2}' | tr -d "\"" | tr -d ","):$IMAGE_TAG
        else
          echo "Private"
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        fi