version: 0.2
phases:
  install:
    commands:
      - yum update -y
      - yum install amazon-linux-extras -y
      - PYTHON=python2 amazon-linux-extras install docker -y
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr-public get-login-password --region $REGION | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo "Building image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $(aws ecr-public describe-repositories --region us-east-1 | grep repositoryUri | awk '{ print $2}' | tr -d "\"" | tr -d ","):$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing image to ECR"
      - docker push $(aws ecr-public describe-repositories --region us-east-1 | grep repositoryUri | awk '{ print $2}' | tr -d "\"" | tr -d ","):$IMAGE_TAG