AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for testing ECR image"
Parameters:
  ECRRepository:
    Type: String
    Default: custom-amazonlinux2
    Description: "ECR repository to use"
  ImageTag:
    Type: String
    Default: latest
    Description: "ECR image tag to use"
  Region:
    Type: String
    Default: us-east-1
    Description: "AWS region to use"
Metadata:
  AWS:CloudFormation::Interface:
    ParameterGroups:
      - Label: ECR
        Parameters:
          - ECRRepository
          - ImageTag
      - Label: AWS
        Parameters:
          - Region
Resources:
  TargetS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "ecr-image-result-bucket"
      Tags:
        - Key: "Name"
          Value: "ECR-Image-Result-bucket"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "artifacts-bucket-v2"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: "artifacts-bucket-v2"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "ecr-image-pipeline"
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: "get-image-from-ecr"
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: "1"
              Configuration:
                RepositoryName: !Ref ECRRepository
                ImageTag: !Ref ImageTag
              OutputArtifacts:
                - Name: "SourceArtifact"
              RunOrder: 1
        - Name: "run-image"
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: "SourceArtifact"
              OutputArtifacts:
                - Name: "BuildArtifact"
      Tags:
        - Key: "Name"
          Value: "ecr-image-pipeline"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ecr-run-project
      Artifacts:
        Type: CODEPIPELINE
        Name: "Artifacts"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: public.ecr.aws/v7l7f0x0/custom-amazonlinux2:latest
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-dummy.yml
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Tags:
        - Key: "Name"
          Value: "ecr-build-project"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: "Name"
          Value: "PipelineRole"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: "Name"
          Value: "CodeBuildServiceRole"
        - Key: "CreatedBy"
          Value: "AWS CFN"