AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for testing ECR image"
Parameters:
  ECRRepository:
    Type: String
    Default: custom-amazonlinux2
    Description: "ECR repository to use"
  ImageTag:
    Type: String
    Default: latest
    Description: "ECR image tag to use"
  Region:
    Type: String
    Default: ap-south-1
    Description: "AWS region to use"
  TargetS3Bucket:
    Type: String
    Default: "ecr-image-result-bucket"
    Description: "S3 bucket to use"
  AWSAccountId:
    Type: String
    Default: 123456789012
    Description: "AWS account ID to use"
Metadata:
  AWS:CloudFormation::Interface:
    ParameterGroups:
      - Label: ECR
        Parameters:
          - ECRRepository
          - ImageTag
      - Label: AWS
        Parameters:
          - Region
          - AWSAccountId
Resources:
  S3Target:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TargetS3Bucket
      Tags:
        - Key: "Name"
          Value: "ECR-Image-Result-bucket"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "artifacts-bucket-v2"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: "artifacts-bucket-v2"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "ecr-image-pipeline"
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: "get-image-from-ecr"
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: "1"
              Configuration:
                RepositoryName: !Ref ECRRepository
                ImageTag: !Ref ImageTag
              OutputArtifacts:
                - Name: "SourceArtifact"
              RunOrder: 1
        - Name: "run-image"
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: "SourceArtifact"
              OutputArtifacts:
                - Name: "BuildArtifact"
      Tags:
        - Key: "Name"
          Value: "ecr-image-pipeline"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ecr-run-project
      Artifacts:
        Type: CODEPIPELINE
        Name: "Artifacts"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 314936303691.dkr.ecr.ap-south-1.amazonaws.com/custom-amazonlinux2:latest
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: "TARGET_S3_BUCKET"
            Value: !Ref TargetS3Bucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub | 
          version: 0.2
          phases:
            pre_build:
              commands:
                - touch result.txt
                - source ~/.bashrc
            build:
              commands:
                - python3.9 --version >> result.txt
                - node --version >> result.txt
                - npm --version >> result.txt
                - aws --version >> result.txt
                - sam --version >> result.txt
                - terraform --version >> result.txt
            post_build:
              commands:
                - echo "Uploading result.txt to S3"
                - aws s3api put-object --bucket $TARGET_S3_BUCKET --key result.txt --body result.txt
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Tags:
        - Key: "Name"
          Value: "ecr-build-project"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: "Name"
          Value: "PipelineRole"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: "Name"
          Value: "CodeBuildServiceRole"
        - Key: "CreatedBy"
          Value: "AWS CFN"
  AmazonCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub arn:aws:codepipeline:${Region}:${AWSAccountId}:${Pipeline}
  AmazonCloudWatchEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        detail:
          action-type: [PUSH]
          image-tag: [!Ref ImageTag]
          repository-name: [!Ref ECRRepository]
          result: [SUCCESS]
        detail-type: [ECR Image Action]
        source: [aws.ecr]
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${Region}:${AWSAccountId}:${Pipeline}
          RoleArn: !GetAtt 
            - AmazonCloudWatchEventRole
            - Arn
          Id: codepipeline-dummy-target